---
language: c

# Need a newer dist in order to install files from debian experimental.
# "trusty" is too old to understand .debs with xz-compressed control and data members.
dist: xenial

addons:
  apt:
    sources:
      # Use debian experimental in order to get a new enough cmocka
      - sourceline: 'deb https://deb.debian.org/debian experimental main'
        key_url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xE0B11894F66AEC98'

    # cmocka is installed separately since debian-experimental needs a -t option, which
    # travis can't provide via this method
    packages:
      - lcov
      - valgrind
      - libarchive-dev

before_install:
  - sudo apt-get install -y -t experimental libcmocka-dev
  - gem install coveralls-lcov

script:
  - ./autogen.sh
  - CFLAGS='-O2 -Wall -Wextra -Werror' ./configure --enable-code-coverage --enable-valgrind

  # Stop after the first failure, to keep the output more readable
  - |
    make check-code-coverage VERBOSE=y &&
    make check-valgrind VERBOSE=y &&
    make distcheck VERBOSE=y

after_success:
  # Upload the lcov info file generated by check-code-coverage
  - coveralls-lcov mkrpm-*.info
